config/routes.rb
Rails.application.routes.draw do
  resources :footerlinks, :path => "admin/footerlinks"
  resources :news_seconds, :path => "admin/news_seconds"
  resources :training_blogs, :path => "admin/training_blogs"
  resources :training_videos, :path => "admin/training_videos"
  resources :news_latests, :path => "admin/news_latests"
  resources :stock_market_updates, :path => "admin/stock_market_updates"
  resources :news_firsts, :path => "admin/news_firsts"
  resources :sliders, :path => "admin/sliders"
  resources :menus, :path => "admin/menus"
  resources :logos, :path => "admin/logos"
  devise_for :users
  
  get '/admin', to: 'stride_admin#admin'

  root to: 'stride#home'

  get '/about', to: 'stride#about_us'
    get '/about/who_we_are', to: 'stride#about_who_we_are'
    get '/about/what_set_as_apart', to: 'stride#about_what_set_as_apart'
    get '/about/our_mission', to: 'stride#about_our_mission'

  get '/growth_tools', to: 'stride#growth_tools'
    get '/growth_tools/training', to: 'stride#growth_tools_training'
    get '/growth_tools/aif', to: 'stride#growth_tools_aif'
    get '/growth_tools/hedge_fund', to: 'stride#growth_tools_hedge_fund'
    get '/growth_tools/financial_planning', to: 'stride#growth_tools_financial_planning'

  get '/market_analysis', to: 'stride#market_analysis'
    get '/market_analysis/daily_updates', to: 'stride#market_analysis_daily_updates'
    get '/market_analysis/statistics', to: 'stride#market_analysis_statistics'
    get '/market_analysis/news', to: 'stride#market_analysis_news'
    get '/market_analysis/strategies', to: 'stride#market_analysis_strategies'

  get '/career', to: 'stride#career'
    get '/career/sales_marketing', to: 'stride#career_sales_marketing'
    get '/career/management_trainee', to: 'stride#career_management_trainee'
    get '/career/research_team', to: 'stride#career_research_team'

  get '/blog', to: 'stride#blog'
  get '/contact', to: 'stride#contact_us'
  get '/budget', to: 'stride#budget'
   


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/news_latest.rb
class NewsLatest < ApplicationRecord
	has_one_attached :image
	validates :name, presence: true
	validates :description, presence: true
    validates_length_of :name, :maximum=>50, :message=>" length of words can not be accepted"
    validates_length_of :description, :maximum=>150, :message=>" length of characters can not be over 150"
    validates :image, presence: true, blob: { content_type: ['image/png', 'image/jpg', 'image/jpeg'], size_range: 1..5000.kilobytes }
	validate :image_type

    private
    def image_type
    	if image.attached? == false
		errors.add(:image, "are missing!")
    	end
	end
end

app/controllers/news_latests_controller.rb
class NewsLatestsController < ApplicationController
  before_action :set_news_latest, only: [:show, :edit, :update, :destroy]

  # GET /news_latests
  # GET /news_latests.json
  def index
    @news_latests = NewsLatest.all
  end

  # GET /news_latests/1
  # GET /news_latests/1.json
  def show
    render :partial => "layouts/404"
  end

  # GET /news_latests/new
  def new
    @news_latest = NewsLatest.new
  end

  # GET /news_latests/1/edit
  def edit
  end

  # POST /news_latests
  # POST /news_latests.json
  def create
    @news_latest = NewsLatest.new(news_latest_params)

    respond_to do |format|
      if @news_latest.save
        format.html { redirect_to action: "index", notice: 'News latest was successfully created.' }
        format.json { render :show, status: :created, location: @news_latest }
      else
        format.html { render :new }
        format.json { render json: @news_latest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news_latests/1
  # PATCH/PUT /news_latests/1.json
  def update
    respond_to do |format|
      if @news_latest.update(news_latest_params)
        format.html { redirect_to action: "index", notice: 'News latest was successfully updated.' }
        format.json { render :show, status: :ok, location: @news_latest }
      else
        format.html { render :edit }
        format.json { render json: @news_latest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news_latests/1
  # DELETE /news_latests/1.json
  def destroy
    @news_latest.destroy
    respond_to do |format|
      format.html { redirect_to news_latests_url, notice: 'News latest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news_latest
      @news_latest = NewsLatest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_latest_params
      params.require(:news_latest).permit(:image, :description, :name)
    end
end

app/helpers/news_latests_helper.rb
module NewsLatestsHelper
end

app/views/news_latests/_form.html.erb
<div class="wrapper ">
  <div class="main-panel">
    <div class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-12">
            <div class="card">
              <div class="card-header card-header-primary">
                <h4 class="card-title">ADD LATEST NEWS</h4>
              </div>
              <div class="card-body">
                <%= form_with(model: news_latest, local: true) do |form| %>
                  <% if news_latest.errors.any? %>
                    <div id="error_explanation">
                      <ul>
                      <% news_latest.errors.full_messages.each do |message| %>
                        <li class="alert"><%= message %></li>
                      <% end %>
                      </ul>
                    </div>
                  <% end %>
                  <div class="row">
                    <div class="col-md-2">
                      <label>Current image</label>
                      <% if news_latest.present? %>
                        <%= image_tag(news_latest.image, class: "img-thumbnail", alt: "Cinque Terre") %>
                      <% end %>
                    </div>
                    <div class="col-md-2">
                      <label>New image</label>
                      <img id="blah" src="" />
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-12">
                      <div class="col-md-3">
                         <span class="btn btn-default btn-file">
                        Browse <%= form.file_field :image, class: "form-control", id: "imgInp" %>
                      </span>
                      </div>
                      <div class="col-md-3">
                        <img id="newimage" src="" />
                      </div>
                    </div>
                  </div>
                  <div class="field">
                    <%= form.label :description %>
                    <%= form.text_field :description, class: "form-control" %>
                  </div>

                  <div class="field">
                    <%= form.label :name %>
                    <%= form.text_field :name, class: "form-control" %>
                  </div>
                  <%= form.submit "Add", class: "btn btn-primary pull-right"%>
                  <div class="clearfix"></div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/news_latests/edit.html.erb
<%= render 'form', news_latest: @news_latest %>

app/views/news_latests/index.html.erb
<div class="wrapper ">
  <div class="main-panel">
    <div class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-12">
            <div class="card">
              <div class="card-header card-header-primary">
                <div class="row">
                  <div class="col-md-10">
                    <h4 class="card-title">LATEST NEWS</h4>
                  </div>
                  <div class="col-md-2">
                    <%= link_to '', new_news_latest_path, class: "fa fa-plus add" %>
                  </div>
                </div>
              </div>
              <div class="card-body">
                <div class="row">
                  <div class="col-md-12">
                    <% @news_latests.each do |news_latest| %>
                      <div class="col-md-3 logo-container">
                        <%= image_tag(news_latest.image, class: "img-thumbnail", alt: "news_latest") %>
                          <p><%= news_latest.description %></p>
                          
                          <h5><%= "By " + news_latest.name %></h5>
                          <p><%= news_latest.created_at.strftime("%d-%m-%Y") %></p>
                          <br/>
                          <center>
                            <%= link_to 'Change', edit_news_latest_path(news_latest), class: "btn btn-raised btn-secondary" %>
                            <%= link_to 'Remove', news_latest, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
                          </center>
                          
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
              <div class="clearfix"></div>    
            </div>
          </div>
        </div> 
      </div>
    </div>
  </div> 
</div>

app/views/news_latests/new.html.erb
<%= render 'form', news_latest: @news_latest %>

app/views/news_latests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @news_latest.description %>
</p>

<p>
  <strong>Name:</strong>
  <%= @news_latest.name %>
</p>

<%= link_to 'Edit', edit_news_latest_path(@news_latest) %> |
<%= link_to 'Back', news_latests_path %>