config/routes.rb
Rails.application.routes.draw do
  resources :footerlinks, :path => "admin/footerlinks"
  resources :news_seconds, :path => "admin/news_seconds"
  resources :training_blogs, :path => "admin/training_blogs"
  resources :training_videos, :path => "admin/training_videos"
  resources :news_latests, :path => "admin/news_latests"
  resources :stock_market_updates, :path => "admin/stock_market_updates"
  resources :news_firsts, :path => "admin/news_firsts"
  resources :sliders, :path => "admin/sliders"
  resources :menus, :path => "admin/menus"
  resources :logos, :path => "admin/logos"
  devise_for :users
  
  get '/admin', to: 'stride_admin#admin'

  root to: 'stride#home'

  get '/about', to: 'stride#about_us'
    get '/about/who_we_are', to: 'stride#about_who_we_are'
    get '/about/what_set_as_apart', to: 'stride#about_what_set_as_apart'
    get '/about/our_mission', to: 'stride#about_our_mission'

  get '/growth_tools', to: 'stride#growth_tools'
    get '/growth_tools/training', to: 'stride#growth_tools_training'
    get '/growth_tools/aif', to: 'stride#growth_tools_aif'
    get '/growth_tools/hedge_fund', to: 'stride#growth_tools_hedge_fund'
    get '/growth_tools/financial_planning', to: 'stride#growth_tools_financial_planning'

  get '/market_analysis', to: 'stride#market_analysis'
    get '/market_analysis/daily_updates', to: 'stride#market_analysis_daily_updates'
    get '/market_analysis/statistics', to: 'stride#market_analysis_statistics'
    get '/market_analysis/news', to: 'stride#market_analysis_news'
    get '/market_analysis/strategies', to: 'stride#market_analysis_strategies'

  get '/career', to: 'stride#career'
    get '/career/sales_marketing', to: 'stride#career_sales_marketing'
    get '/career/management_trainee', to: 'stride#career_management_trainee'
    get '/career/research_team', to: 'stride#career_research_team'

  get '/blog', to: 'stride#blog'
  get '/contact', to: 'stride#contact_us'
  get '/budget', to: 'stride#budget'
   


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/footerlink.rb
class Footerlink < ApplicationRecord
	validates :name, presence: true
end

app/controllers/footerlinks_controller.rb
class FooterlinksController < ApplicationController
  before_action :set_footerlink, only: [:show, :edit, :update, :destroy]
 
  # GET /footerlinks.json
  def index
    @footerlinks = Footerlink.all
  end

  # GET /footerlinks/1
  # GET /footerlinks/1.json
  def show
    render :partial => "layouts/404"
  end

  # GET /footerlinks/new
  def new
    @footerlink = Footerlink.new
  end

  # GET /footerlinks/1/edit
  def edit
  end

  # POST /footerlinks
  # POST /footerlinks.json
  def create
    @footerlink = Footerlink.new(footerlink_params)

    respond_to do |format|
      if @footerlink.save
        format.html { redirect_to action: "index", notice: 'Footerlink was successfully created.' }
        format.json { render :show, status: :created, location: @footerlink }
      else
        format.html { render :new }
        format.json { render json: @footerlink.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /footerlinks/1
  # PATCH/PUT /footerlinks/1.json
  def update
    respond_to do |format|
      if @footerlink.update(footerlink_params)
        format.html { redirect_to action: "index", notice: 'Footerlink was successfully updated.' }
        format.json { render :show, status: :ok, location: @footerlink }
      else
        format.html { render :edit }
        format.json { render json: @footerlink.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /footerlinks/1
  # DELETE /footerlinks/1.json
  def destroy
    @footerlink.destroy
    respond_to do |format|
      format.html { redirect_to footerlinks_url, notice: 'Footerlink was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_footerlink
      @footerlink = Footerlink.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def footerlink_params
      params.require(:footerlink).permit(:name)
    end
end

app/helpers/footerlinks_helper.rb
module FooterlinksHelper
end

app/views/footerlinks/_form.html.erb
<div class="wrapper ">
  <div class="main-panel">
    <div class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-12">
            <div class="card">
              <div class="card-header card-header-primary">
                <h4 class="card-title">ADD EXTRA LINKS</h4>
              </div>
              <div class="card-body">
                <%= form_with(model: footerlink, local: true) do |form| %>
                  <% if footerlink.errors.any? %>
                    <div id="error_explanation">
                      <h2><%= pluralize(footerlink.errors.count, "error") %> prohibited this footerlink from being saved:</h2>

                      <ul>
                      <% footerlink.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                      <% end %>
                      </ul>
                    </div>
                  <% end %>
                  <br>
                  <br>
                  <div class="row">
                    <div class="col-md-1 offset-3">
                      <%= form.label :name, class: "footer-name" %>
                    </div>
                    <div class="col-md-4 ">
                      <div class="field">
                        <%= form.text_field :name, class: "form-control" %>
                      </div>                 
                    </div>
                    <div class="col-md-1">
                      <%= form.submit "Add", class: "btn btn-primary pull-right"%>
                    </div>
                  </div>
                  <br>
                  
                  <div class="clearfix"></div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/footerlinks/edit.html.erb
<%= render 'form', footerlink: @footerlink %>

app/views/footerlinks/index.html.erb
<div class="wrapper ">
  <div class="main-panel">
    <div class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-12">
            <div class="card">
              <div class="card-header card-header-primary">
                <div class="row">
                  <div class="col-md-10">
                    <h4 class="card-title">FOOTER LINKS</h4>
                  </div>
                  <div class="col-md-2">
                    <%= link_to '', new_footerlink_path, class: "fa fa-plus add" %>
                  </div>
                </div>
              </div>
              <div class="card-body">
                <div class="row">
                  <div class="col-md-12">
                    <table class="table">
                      
                      <tbody>
                        <% @footerlinks.each do |footerlink| %>
                          <tr>
                            <td><%= footerlink.name %></td>
                            <td style="text-align: right;"><%= link_to '', edit_footerlink_path(footerlink), class: "fa fa-pencil" %>
                            <%= link_to '', footerlink, method: :delete, data: { confirm: 'Are you sure?' }, class: "fa fa-trash" %></td>
                          </tr>
                        <% end %>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            <div class="clearfix"></div> 
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
                       

app/views/footerlinks/new.html.erb
<%= render 'form', footerlink: @footerlink %>

app/views/footerlinks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @footerlink.name %>
</p>

<%= link_to 'Edit', edit_footerlink_path(@footerlink) %> |
<%= link_to 'Back', footerlinks_path %>