config/routes.rb
Rails.application.routes.draw do
  resources :footerlinks, :path => "admin/footerlinks"
  resources :news_seconds, :path => "admin/news_seconds"
  resources :training_blogs, :path => "admin/training_blogs"
  resources :training_videos, :path => "admin/training_videos"
  resources :news_latests, :path => "admin/news_latests"
  resources :stock_market_updates, :path => "admin/stock_market_updates"
  resources :news_firsts, :path => "admin/news_firsts"
  resources :sliders, :path => "admin/sliders"
  resources :menus, :path => "admin/menus"
  resources :logos, :path => "admin/logos"
  devise_for :users
  
  get '/admin', to: 'stride_admin#admin'

  root to: 'stride#home'

  get '/about', to: 'stride#about_us'
    get '/about/who_we_are', to: 'stride#about_who_we_are'
    get '/about/what_set_as_apart', to: 'stride#about_what_set_as_apart'
    get '/about/our_mission', to: 'stride#about_our_mission'

  get '/growth_tools', to: 'stride#growth_tools'
    get '/growth_tools/training', to: 'stride#growth_tools_training'
    get '/growth_tools/aif', to: 'stride#growth_tools_aif'
    get '/growth_tools/hedge_fund', to: 'stride#growth_tools_hedge_fund'
    get '/growth_tools/financial_planning', to: 'stride#growth_tools_financial_planning'

  get '/market_analysis', to: 'stride#market_analysis'
    get '/market_analysis/daily_updates', to: 'stride#market_analysis_daily_updates'
    get '/market_analysis/statistics', to: 'stride#market_analysis_statistics'
    get '/market_analysis/news', to: 'stride#market_analysis_news'
    get '/market_analysis/strategies', to: 'stride#market_analysis_strategies'

  get '/career', to: 'stride#career'
    get '/career/sales_marketing', to: 'stride#career_sales_marketing'
    get '/career/management_trainee', to: 'stride#career_management_trainee'
    get '/career/research_team', to: 'stride#career_research_team'

  get '/blog', to: 'stride#blog'
  get '/contact', to: 'stride#contact_us'
  get '/budget', to: 'stride#budget'
   


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/stock_market_update.rb
class StockMarketUpdate < ApplicationRecord
	has_one_attached :image
	validates :description, presence: true
    validates_length_of :description, :maximum=>150, :message=>" length of characters can not be over 150"
    validates :image, presence: true, blob: { content_type: ['image/png', 'image/jpg', 'image/jpeg'], size_range: 1..5000.kilobytes }
    validate :image_type

    private
    def image_type
    	if image.attached? == false
		errors.add(:image, "are missing!")
    	end
	end

end

app/controllers/stock_market_updates_controller.rb
class StockMarketUpdatesController < ApplicationController
  before_action :set_stock_market_update, only: [:show, :edit, :update, :destroy]

  # GET /stock_market_updates
  # GET /stock_market_updates.json
  def index
    @stock_market_updates = StockMarketUpdate.all
  end

  # GET /stock_market_updates/1
  # GET /stock_market_updates/1.json
  def show
     render :partial => "layouts/404"
  end

  # GET /stock_market_updates/new
  def new
    @stock_market_update = StockMarketUpdate.new
  end

  # GET /stock_market_updates/1/edit
  def edit
  end

  # POST /stock_market_updates
  # POST /stock_market_updates.json
  def create
    @stock_market_update = StockMarketUpdate.new(stock_market_update_params)

    respond_to do |format|
      if @stock_market_update.save
        format.html { redirect_to action: "index", notice: 'Stock market update was successfully created.' }
        format.json { render :show, status: :created, location: @stock_market_update }
      else
        format.html { render :new }
        format.json { render json: @stock_market_update.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stock_market_updates/1
  # PATCH/PUT /stock_market_updates/1.json
  def update
    respond_to do |format|
      if @stock_market_update.update(stock_market_update_params)
        format.html { redirect_to action: "index", notice: 'Stock market update was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock_market_update }
      else
        format.html { render :edit }
        format.json { render json: @stock_market_update.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stock_market_updates/1
  # DELETE /stock_market_updates/1.json
  def destroy
    @stock_market_update.destroy
    respond_to do |format|
      format.html { redirect_to stock_market_updates_url, notice: 'Stock market update was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock_market_update
      @stock_market_update = StockMarketUpdate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stock_market_update_params
      params.require(:stock_market_update).permit(:image, :description)
    end
end

app/helpers/stock_market_updates_helper.rb
module StockMarketUpdatesHelper
end

app/views/stock_market_updates/_form.html.erb
<div class="wrapper ">
  <div class="main-panel">
    <div class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-12">
            <div class="card">
              <div class="card-header card-header-primary">
                <h4 class="card-title">ADD STOCK UPDATES</h4>
              </div>
              <div class="card-body">
                <%= form_with(model: stock_market_update, local: true) do |form| %>
                  <% if stock_market_update.errors.any? %>
                    <div id="error_explanation">
                      <ul>
                      <% stock_market_update.errors.full_messages.each do |message| %>
                        <li class="alert"><%= message %></li>
                      <% end %>
                      </ul>
                    </div>
                  <% end %>
                  <div class="row">
                    <div class="col-md-2">
                      <label>Current image</label>
                      <% if stock_market_update.present? %>
                        <%= image_tag(stock_market_update.image, class: "img-thumbnail", alt: "Cinque Terre") %>
                      <% end %>
                    </div>
                    <div class="col-md-2">
                      <label>New image</label>
                      <img id="blah" src="" />
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-12">
                      <div class="col-md-3">
                         <span class="btn btn-default btn-file">
                        Browse <%= form.file_field :image, class: "form-control", id: "imgInp" %>
                      </span>
                      </div>
                      <div class="col-md-3">
                        <img id="newimage" src="" />
                      </div>
                    </div>
                  </div>
                  <div class="field">
                    <%= form.label :description %>
                    <%= form.text_field :description, class: "form-control" %>
                  </div>
                  <%= form.submit "Add", class: "btn btn-primary pull-right"%>
                  <div class="clearfix"></div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/stock_market_updates/edit.html.erb
<%= render 'form', stock_market_update: @stock_market_update %>

app/views/stock_market_updates/index.html.erb
<div class="wrapper ">
  <div class="main-panel">
    <div class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-12">
            <div class="card">
              <div class="card-header card-header-primary">
                <div class="row">
                  <div class="col-md-11">
                    <h4 class="card-title">NEWS</h4>
                  </div>
                  <div class="col-md-1">
                    <%= link_to '', new_stock_market_update_path, class: "fa fa-plus add" %>
                  </div>
                </div>
              </div>
              <div class="card-body">
                <div class="row">
                  <div class="col-md-12">
                    <% @stock_market_updates.each do |stock_market_update| %>
                      <div class="col-md-3 logo-container">
                        <%= image_tag(stock_market_update.image, class: "img-thumbnail", alt: "stock_market_update") %>
                        
                          <p><%= stock_market_update.description %></p>
                          <br/>
                          <center>
                            <%= link_to 'Change', edit_stock_market_update_path(stock_market_update), class: "btn btn-raised btn-secondary" %>
                            <%= link_to 'Remove', stock_market_update, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
                          </center>
                          
                       
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
              <div class="clearfix"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/stock_market_updates/new.html.erb
<%= render 'form', stock_market_update: @stock_market_update %>

app/views/stock_market_updates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @stock_market_update.description %>
</p>

<%= link_to 'Edit', edit_stock_market_update_path(@stock_market_update) %> |
<%= link_to 'Back', stock_market_updates_path %>