config/routes.rb
Rails.application.routes.draw do
  resources :footerlinks, :path => "admin/footerlinks"
  resources :news_seconds, :path => "admin/news_seconds"
  resources :training_blogs, :path => "admin/training_blogs"
  resources :training_videos, :path => "admin/training_videos"
  resources :news_latests, :path => "admin/news_latests"
  resources :stock_market_updates, :path => "admin/stock_market_updates"
  resources :news_firsts, :path => "admin/news_firsts"
  resources :sliders, :path => "admin/sliders"
  resources :menus, :path => "admin/menus"
  resources :logos, :path => "admin/logos"
  devise_for :users
  
  get '/admin', to: 'stride_admin#admin'

  root to: 'stride#home'

  get '/about', to: 'stride#about_us'
    get '/about/who_we_are', to: 'stride#about_who_we_are'
    get '/about/what_set_as_apart', to: 'stride#about_what_set_as_apart'
    get '/about/our_mission', to: 'stride#about_our_mission'

  get '/growth_tools', to: 'stride#growth_tools'
    get '/growth_tools/training', to: 'stride#growth_tools_training'
    get '/growth_tools/aif', to: 'stride#growth_tools_aif'
    get '/growth_tools/hedge_fund', to: 'stride#growth_tools_hedge_fund'
    get '/growth_tools/financial_planning', to: 'stride#growth_tools_financial_planning'

  get '/market_analysis', to: 'stride#market_analysis'
    get '/market_analysis/daily_updates', to: 'stride#market_analysis_daily_updates'
    get '/market_analysis/statistics', to: 'stride#market_analysis_statistics'
    get '/market_analysis/news', to: 'stride#market_analysis_news'
    get '/market_analysis/strategies', to: 'stride#market_analysis_strategies'

  get '/career', to: 'stride#career'
    get '/career/sales_marketing', to: 'stride#career_sales_marketing'
    get '/career/management_trainee', to: 'stride#career_management_trainee'
    get '/career/research_team', to: 'stride#career_research_team'

  get '/blog', to: 'stride#blog'
  get '/contact', to: 'stride#contact_us'
  get '/budget', to: 'stride#budget'
   


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/footerlink.rb
class Footerlink < ApplicationRecord
	validates :name, presence: true
end

app/models/logo.rb
class Logo < ApplicationRecord
	has_one_attached :image
	validates :about, presence: true
    validates :contact, presence: true, length: { is: 10 }
    validates :email, presence: true
    validates_length_of :about, :maximum=>150, :message=>"Length of words can not be accepted"
   	validates :image, presence: true, blob: { content_type: ['image/png', 'image/jpg', 'image/jpeg'], size_range: 1..5000.kilobytes }

    validate :image_type

    private

	def image_type
	  if image.attached? == false
		errors.add(:image, "are missing!")
	  end
	end
end

app/models/menu.rb
class Menu < ApplicationRecord
	has_many :submenus, dependent: :destroy, inverse_of: :menu
	
	accepts_nested_attributes_for :submenus, :allow_destroy => true, reject_if: :all_blank

  	validates_associated :submenus

  	validates :name, presence: true
	
   
end

app/models/news_first.rb
class NewsFirst < ApplicationRecord
	has_one_attached :image
	validates :heading, presence: true
	validates :description, presence: true
    validates_length_of :heading, :maximum=>50, :message=>" length of words can not be accepted"
    validates_length_of :description, :maximum=>250, :message=>" length of characters can not be over 150"
    validates :image, presence: true, blob: { content_type: ['image/png', 'image/jpg', 'image/jpeg'], size_range: 1..5000.kilobytes }

    validate :image_type

    private
    def image_type
    	if image.attached? == false
		errors.add(:image, "are missing!")
    	end
	end
end

app/models/news_latest.rb
class NewsLatest < ApplicationRecord
	has_one_attached :image
	validates :name, presence: true
	validates :description, presence: true
    validates_length_of :name, :maximum=>50, :message=>" length of words can not be accepted"
    validates_length_of :description, :maximum=>150, :message=>" length of characters can not be over 150"
    validates :image, presence: true, blob: { content_type: ['image/png', 'image/jpg', 'image/jpeg'], size_range: 1..5000.kilobytes }
	validate :image_type

    private
    def image_type
    	if image.attached? == false
		errors.add(:image, "are missing!")
    	end
	end
end

app/models/news_second.rb
class NewsSecond < ApplicationRecord
	has_one_attached :image
	validates :heading, presence: true
	validates :description, presence: true
    validates_length_of :heading, :maximum=>50, :message=>" Length of words can not be accepted"
    validates_length_of :description, :maximum=>150, :message=>" length of characters can not be over 150"
    validates :image, presence: true, blob: { content_type: ['image/png', 'image/jpg', 'image/jpeg'], size_range: 1..5000.kilobytes }
	validate :image_type

    private
    def image_type
    	if image.attached? == false
		errors.add(:image, "are missing!")
    	end
	end
end

app/models/slider.rb
class Slider < ApplicationRecord
	has_one_attached :image
	validates :heading, presence: true
	validates :description, presence: true
    validates_length_of :heading, :maximum=>50, :message=>" length of words can not be accepted"
    validates_length_of :description, :maximum=>150, :message=>" length of characters can not be over 150"
    validates :image, presence: true, blob: { content_type: ['image/png', 'image/jpg', 'image/jpeg'], size_range: 1..5000.kilobytes }
	validate  :image_type

    private
    def image_type
    	if image.attached? == false
		errors.add(:image, "are missing!")
    	end
	end
end

app/models/stock_market_update.rb
class StockMarketUpdate < ApplicationRecord
	has_one_attached :image
	validates :description, presence: true
    validates_length_of :description, :maximum=>150, :message=>" length of characters can not be over 150"
    validates :image, presence: true, blob: { content_type: ['image/png', 'image/jpg', 'image/jpeg'], size_range: 1..5000.kilobytes }
    validate :image_type

    private
    def image_type
    	if image.attached? == false
		errors.add(:image, "are missing!")
    	end
	end

end

app/models/submenu.rb
class Submenu < ApplicationRecord
	belongs_to :menu, inverse_of: :submenus
end

app/models/training_blog.rb
class TrainingBlog < ApplicationRecord
	has_one_attached :image
	validates :name, presence: true
	validates :description, presence: true
    validates_length_of :name, :maximum=>50, :message=>" length of words can not be accepted"
    validates_length_of :description, :maximum=>150, :message=>" length of characters can not be over 150"
    validates :image, presence: true, blob: { content_type: ['image/png', 'image/jpg', 'image/jpeg'], size_range: 1..5000.kilobytes }

    validate :image_type

    private
    def image_type
    	if image.attached? == false
		errors.add(:image, "are missing!")
    	end
	end
end

app/models/training_video.rb
class TrainingVideo < ApplicationRecord
	has_one_attached :image
	validates :link, presence: true
	validates :caption, presence: true
    validates_length_of :link, :maximum=>50, :message=>" length of words can not be accepted"
    validates_length_of :caption, :maximum=>80, :message=>" length of characters can not be over 30"
    validates :image, presence: true, blob: { content_type: ['image/png', 'image/jpg', 'image/jpeg'], size_range: 1..5000.kilobytes }

    validate :image_type

   private
    def image_type
    	if image.attached? == false
		errors.add(:image, "are missing!")
    	end
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/footerlinks_helper.rb
module FooterlinksHelper
end

app/helpers/logos_helper.rb
module LogosHelper
end

app/helpers/menus_helper.rb
module MenusHelper
	def link_to_add_row(name, f, association, **args)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize, f: builder);
    end
    link_to(name, '#', class: "add_fields " + args[:class], data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/helpers/news_firsts_helper.rb
module NewsFirstsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/sliders_helper.rb
module SlidersHelper
end

app/views/layouts/_404.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The page you were looking for doesn't exist (404)</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <style>
 
  </style>
</head>

<body class="rails-default-error-page">
  <!-- This file lives in public/404.html -->
  <div class="dialog">
    <h3>404</h3>
    <div>
      <h1>The page you were looking for doesn't exist.</h1>
      <p>You may have mistyped the address or the page may have moved.</p>
    </div>
    <p>If you are the application owner check the logs for more information.</p>
  </div>
</body>
</html>

app/views/layouts/_navbar.html.erb
<!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
    <div class="container-fluid">
      <div class="navbar-wrapper">
        <a class="navbar-brand" href="#pablo">Dashboard</a>
      </div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
        <span class="sr-only">Toggle navigation</span>
        <span class="navbar-toggler-icon icon-bar"></span>
        <span class="navbar-toggler-icon icon-bar"></span>
        <span class="navbar-toggler-icon icon-bar"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end">
        <form class="navbar-form1">
          <div class="input-group no-border">
            <input type="text" value="" class="form-control" placeholder="Search...">
            <button type="submit" class="btn btn-white btn-round btn-just-icon">
              <i class="material-icons">search</i>
              <div class="ripple-container"></div>
            </button>
          </div>
        </form>
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="#pablo">
              <i class="material-icons">dashboard</i>
              <p class="d-lg-none d-md-block">
                Stats
              </p>
            </a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="material-icons">notifications</i>
              <span class="notification">5</span>
              <p class="d-lg-none d-md-block">
                Some Actions
              </p>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="#">Mike John responded to your email</a>
              <a class="dropdown-item" href="#">You have 5 new tasks</a>
              <a class="dropdown-item" href="#">You're now friend with Andrew</a>
              <a class="dropdown-item" href="#">Another Notification</a>
              <a class="dropdown-item" href="#">Another One</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link" href="#pablo" id="navbarDropdownProfile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="material-icons">person</i>
              <p class="d-lg-none d-md-block">
                Account
              </p>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownProfile">
                

                 <%= link_to "Profile",user_session_path, class: "dropdown-item"  %> 
                
                  <%= link_to "Setting", edit_user_registration_path, class: "dropdown-item"  %>
                  <div class="dropdown-divider"></div>
                
                  <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item"  %>
                </div>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <!-- End Navbar -->

<style>
  
form.navbar-form1 {
    width: 14%;
  float: left; 
  display: none;
}

ul.navbar-nav {
    float: right;
}
.dropdown-menu .dropdown-item, .dropdown-menu li>a {
    position: relative;
    width: auto;
    display: flex;
    flex-flow: nowrap;
    align-items: center;
    color: #333;
    font-weight: 400;
    text-decoration: none;
    font-size: 13px;
    border-radius: .125rem;
    margin: 0 .3125rem;
    transition: all .15s linear;
    min-width: 7rem;
    padding: .625rem 1.25rem;
    overflow: hidden;
    line-height: 1.428571;
    text-overflow: ellipsis;
    word-wrap: break-word;
}
.navbar .collapse .navbar-nav .nav-item .nav-link .fa, .navbar .collapse .navbar-nav .nav-item .nav-link .material-icons {
    font-size: 2.25rem;
    max-width: 24px;
    margin-top: -1.1em;
}

.navbar > .container .navbar-brand, .navbar > .container-fluid .navbar-brand {
    margin-left: 15px;
}

.navbar .navbar-brand {
    position: relative;
    color: inherit;
    height: 50px;
    font-size: 2.125rem;
    line-height: 30px;
    padding: .625rem 0;
    font-weight: 300;
    margin-left: 1rem;
}

</style>

app/views/layouts/_sidebar.html.erb
    <div class="sidebar" data-color="purple" data-background-color="white" data-image="../assets/img/sidebar-1.jpg">
      <div class="logo">
        <center><%= image_tag("logo-footer-3.png", style: "width: 140px", class: "simple-text logo-normal") %></center>
      </div>
      <div class="sidebar-wrapper">
         <ul class="nav">
            <li class="nav-item ">
              <a class="nav-link" href="/admin">
                <i class="material-icons">apps</i>
                <p>dashboard</p>
              </a>
            </li>
            <li class="nav-item ">
              <a class="nav-link" href="#" data-toggle="collapse" data-target="#header">
                <i class="material-icons">storage</i>
                <p style="cursor: pointer;">header</p>
              </a>
                <div id="header" class="collapse content" style="background-color: rgba(15, 23, 36, 0.53);">
                  <ul style="list-style-type: none;">
                    <li class="nav-item">
                      <a class="nav-link" href="/admin/logos">
                        <i class="material-icons">bubble_chart</i>
                        <p>logo</p>
                      </a>
                    </li>
                    <li class="nav-item ">
                      <a class="nav-link" href="/admin/menus">
                        <i class="material-icons">menu</i>
                        <p>menu</p>
                      </a>
                    </li>
                  </ul>
                </div>
            </li>
            <li class="nav-item ">
              <a class="nav-link" href="#" data-toggle="collapse" data-target="#body">
                <i class="material-icons">library_books</i>
                <p style="cursor: pointer;">content</p>
              </a>
                <div id="body" class="collapse content" style="background-color: rgba(15, 23, 36, 0.53);">
                  <ul style="list-style-type: none;">
                    <li class="nav-item ">
                      <a class="nav-link" href="/admin/sliders">
                        <i class="material-icons">code</i>
                        <p>slider</p>
                      </a>
                    </li>
                    <li class="nav-item ">
                      <a class="nav-link" href="/admin/news_firsts">
                        <i class="material-icons">event_note</i>
                        <p>first news</p>
                      </a>
                    </li>
                    <li class="nav-item ">
                      <a class="nav-link" href="/admin/news_seconds">
                        <i class="material-icons">import_contacts</i>
                        <p>second news</p>
                      </a>
                    </li>
                    <li class="nav-item ">
                      <a class="nav-link" href="/admin/news_latests">
                        <i class="material-icons">local_library</i>
                        <p>latest news</p>
                      </a>
                    </li>
                    <li class="nav-item ">
                      <a class="nav-link" href="/admin/stock_market_updates">
                        <i class="material-icons">business</i>
                        <p>stock updation</p>
                      </a>
                    </li>
                    <li class="nav-item ">
                      <a class="nav-link" href="/admin/training_blogs">
                        <i class="material-icons">textsms</i>
                        <p>training blog</p>
                      </a>
                    </li>
                    <li class="nav-item ">
                      <a class="nav-link" href="/admin/training_videos">
                        <i class="material-icons">video_library</i>
                        <p>video</p>
                      </a>
                    </li>
                  </ul>
                </div>
            </li>
            <li class="nav-item ">
              <a class="nav-link" href="/admin/footerlinks">
                <i class="material-icons">layers</i>
                <p>footer</p>
              </a>
            </li>
            <li class="nav-item ">
              <a class="nav-link" href="">
                <i class="material-icons">library_books</i>
                <p>typography</p>
              </a>
            </li>
            <li class="nav-item ">
              <a class="nav-link" href="">
                <i class="material-icons">location_ons</i>
                <p>maps</p>
              </a>
            </li>
            <li class="nav-item ">
              <a class="nav-link" href="">
                <i class="material-icons">notifications</i>
                <p>notification</p>
              </a>
            </li>
          </ul>
      </div>
    </div>
    

app/views/layouts/_stride_footer.html.erb
<footer>
  <div class="footer-1">
    <div class="container">
      <div class="row">
        <div class="col-md-3 col-sm-6 col-12">
          <a href="#"><%= image_tag(Logo.last.image, :width => '70px', class: "main-logo", :alt=> "logo", id: "footer_logo") %></a>
          <p class="mt-20"><%= Logo.last.about %></p>
          <ul class="social-links-footer">
            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="fa fa-instagram"></i></a></li>
            <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
          </ul>
        </div>
        <div class="col-md-3 col-sm-6 col-12">
          <h2>Extra Links</h2>
          <div class="row mt-25">
            <div class="col-md-6 col-sm-6">
              <ul class="footer-nav">
                <!-- <li><a href="#">About Us</a></li>
                <li><a href="#">Services</a></li>
                <li><a href="#">Our approach</a></li>
                <li><a href="#">Business</a></li>
                <li><a href="#">Consulting</a></li>
                <li><a href="#">Latest News</a></li>
                <li><a href="#">Contact us</a></li>
                <li><a href="#">Our team</a></li>
                 -->
                 <% Footerlink.all.each do |footer| %>
                  <li><a href="#"><%= footer.name %></a></li>
                  <% end %>
              </ul>
            </div>
            
            </div>
            </div>
            <div class="col-md-3 col-sm-6 col-12">
                <h2>Recent news</h2>
                        <ul class="footer-news mt-25">
                            <% StockMarketUpdate.last(2).each do |stock| %>
                              <li> <a href="#"><%= stock.description %></a> <strong><i class="fa fa-calendar"></i><%= stock.created_at.strftime("%d/%m/%y") %></strong> </li>
                            <% end %>
                            
                        </ul>
                    </div>
                    <div class="col-md-3 col-sm-6 col-12">
                        <h2>Subscribe</h2>
                        <form class="footer-subscribe-form mt-25">
                            <div class="d-table full-width">
                                <div class="d-table-cell">
                                    <input type="text" placeholder="Your Email adress"> </div>
                                <div class="d-table-cell">
                                    <button type="submit"><i class="fa fa-envelope"></i></button>
                                </div>
                            </div>
                        </form>
                        <p class="mt-10">Get latest updates and offers.</p>
                    </div>
                </div>
                <div class="footer-1-bar">
                    <center>SpecThemes © 2019. All Rights Reserved.</center>
                </div>
            </div>
        </div>
    </footer>

app/views/layouts/_stride_header.html.erb
<div id="preloader">
  <div class="lds-ellipsis">
      <div></div>
      <div></div>
      <div></div>
      <div></div>
  </div>
</div>
<div id="top-bar" class="hidden-md-down">
  <div class="container">
      <div class="row">
          <div class="col-md-9 col-12">
              <ul class="top-bar-info">
                  <li><i class="fa fa-phone"></i> Phone: <%= Logo.last.contact %></li>
                  <li><i class="fa fa-map-marker"></i><%= Logo.last.location %></li>
                  <li><i class="fa fa-envelope"></i>Email: <%= Logo.last.email %></li>
              </ul>
          </div>
          <div class="col-md-3 col-12">
            <ul class="social-icons hidden-sm">
              <% if user_signed_in? %>
                <li><%= link_to "logout", destroy_user_session_path(@user), method: :delete, style: "pull-right" %></li>
              <% else %>
                <!-- <li><a href="#" data-toggle="modal" data-target="#myModal">Sign In  /  Free Sign Up</li> -->
                 <li><%= link_to "login", new_user_session_path %></li>
                <li><%= link_to "sigup", new_user_session_path %></li>
              <% end %>
             
            </ul>
          </div>
          
      </div>
   </div>
</div>
<header>
  <nav id="navigation4" class="container navigation">
    <div class="nav-header">
      <%= link_to image_tag(Logo.last.image, class: "main-logo", :alt=> "logo", id: "main_logo", style: "width: 145px; height: 50px;"), root_path, class: "nav-brand" %>
      <div class="nav-toggle"></div>
    </div>
    <div class="nav-menus-wrapper">
      <ul class="nav-menu align-to-right">
        <li><%= link_to Menu.all[0].name, root_path %></li>
        <li>
          <%= link_to Menu.all[1].name, about_path %>
          <ul class="nav-dropdown">
            <li><%= link_to Menu.all[1].submenus[0].name, about_who_we_are_path %></li>
            <li><%= link_to Menu.all[1].submenus[1].name, about_what_set_as_apart_path %></li>
            <li><%= link_to Menu.all[1].submenus[2].name, about_our_mission_path %></li>
          </ul>
        </li>
        <li>
          <%== link_to Menu.all[2].name, growth_tools_path %>
          <ul class="nav-dropdown">
            <li><%= link_to Menu.all[2].submenus[0].name, growth_tools_training_path  %></li>
            <li><%= link_to Menu.all[2].submenus[1].name, growth_tools_aif_path  %></li>
            <li><%= link_to Menu.all[2].submenus[2].name, growth_tools_hedge_fund_path %></li>
            <li><%= link_to Menu.all[2].submenus[3].name, growth_tools_financial_planning_path %></li>
          </ul>
        </li>
        <li>
          <%== link_to Menu.all[3].name, market_analysis_path %>
          <ul class="nav-dropdown">
            <li><%= link_to Menu.all[3].submenus[0].name, market_analysis_daily_updates_path %></li>
            <li><%= link_to Menu.all[3].submenus[1].name, market_analysis_statistics_path %></li>
            <li><%= link_to Menu.all[3].submenus[2].name, market_analysis_news_path %></li>
            <li><%= link_to Menu.all[3].submenus[3].name, market_analysis_strategies_path %></li>
          </ul>
        </li>
        <li>
          <%== link_to Menu.all[4].name, career_path %>
          <ul class="nav-dropdown">
            <li><%= link_to Menu.all[4].submenus[0].name, career_sales_marketing_path %></li>
            <li><%= link_to Menu.all[4].submenus[1].name, career_management_trainee_path %></li>
            <li><%= link_to Menu.all[4].submenus[2].name, career_research_team_path %></li>
          </ul>
        </li>
        <li><%== link_to Menu.all[5].name, blog_path %></li>
        <li> <%= link_to Menu.all[6].name, budget_path %></li>
        <li><%== link_to Menu.all[7].name, contact_path %></li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="../assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="../assets/img/favicon.png">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <title>Stride</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>

    <%= javascript_include_tag 'application' %>
     <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />

    
    <!--  -->
  </head>

  <body>


    <% if user_signed_in? %>
      <% if current_user.admin? %>
        <%= render 'layouts/sidebar' %>
        <div class="main-panel">
           <%= render 'layouts/navbar' %>
        </div>
        <%= yield %>

      <% end %>
      
    <% else %>
      <% if user_signed_in? == false %>
        <%= render "layouts/404" %>
      <% end %>
      
    <% end %>



    
    
    
  </body>
</html>

app/views/layouts/stride.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="../assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="../assets/img/favicon.png">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <title>Stride</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
  <link href="http://yoursite.com/themify-icons.css" rel="stylesheet">
  </head>

  <body>
    <%= render 'layouts/stride_header' %>
    <%= yield %>
    <%= render 'layouts/stride_footer' %>

  </body>
</html>

app/views/layouts/user.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="../assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="../assets/img/favicon.png">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <title>Stride</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />

    
    <!--  -->
  </head>

  <body>

        <%= yield %>




    
    
    
  </body>
</html>